apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - image: ghcr.io/simon2k/landing:sha-72c7e54
        name: landing
        ports:
        - containerPort: 3000
